---
title: GisException Class
type: docs
weight: 1330
url: /python-net/aspose.gis/gisexception/
---

**Summary:** The exception that is thrown when an error occurs during GIS data processing.

**Module:** [aspose.gis](/psd/python-net/aspose.gis/)

**Full Name:** aspose.gis.GisException

**Aspose.PSD Version:** 24.12.0

## **Constructors**
| **Name** | **Description** |
| :- | :- |
| [GisException()](#GisException__1) | Initializes a new instance of the [GisException](/psd/python-net/aspose.gis/gisexception/) class. |
| [GisException(message)](#GisException_message_2) | Initializes a new instance of the [GisException](/psd/python-net/aspose.gis/gisexception/) class. |


### Constructor: GisException() {#GisException__1}


```
 GisException() 
```

Initializes a new instance of the [GisException](/psd/python-net/aspose.gis/gisexception/) class.

### Constructor: GisException(message) {#GisException_message_2}


```
 GisException(message) 
```

Initializes a new instance of the [GisException](/psd/python-net/aspose.gis/gisexception/) class.

**Parameters:**

| Parameter | Type | Description |
| :- | :- | :- |
| message | string | The message that describes the error. |

